### ISSUE TITLE
Loading error: IteratorTest is missing

### ISSUE THREAD

**Issue by tinchodias** [juliendelplanque/TreeQuery#7]
Smells like Baseline needs to declare a dependency

**Comment by juliendelplanque** [comment]
Hello!

I will try to reproduce locally and fix it.

**Comment by tinchodias** [comment]
Thanks! I evaluated this in a Pharo 8 (not from today, but it looks unrelated):

~~~Smalltalk
Metacello new
    repository: 'github://JulienDelplanque/TreeQuery/src';
    baseline: 'TreeQuery';
    load
~~~

**Comment by juliendelplanque** [comment]
I just checked locally and [triggered a build on the CI](https://travis-ci.org/juliendelplanque/TreeQuery/builds/603960035) and the error does not appear.

Did you pulled latest changes from TreeQuery git repository ?

```Smalltalk
Metacello new
    repository: 'github://JulienDelplanque/TreeQuery/src';
    baseline: 'TreeQuery';
    onUpgrade: #useIncoming;
    load
```

**Comment by tinchodias** [comment]
I got the same when I tried your script in a more recent P8 (downloaded last Friday).

What is the package for `IteratorTest` in your image?

**Comment by juliendelplanque** [comment]
It is a class:
<img width="1440" alt="Capture d’écran 2019-10-28 à 18 32 24" src="https://user-images.githubusercontent.com/8260456/67702078-62957380-f9b1-11e9-8c1f-18644471f20d.png">

**Comment by tinchodias** [comment]
OKey, I see that TreeQuery's baseline mentions [Iterators project as external dependency](https://github.com/juliendelplanque/TreeQuery/blob/master/src/BaselineOfTreeQuery/BaselineOfTreeQuery.class.st) but evidently it's not loading it before loading the subclass of `IteratorTest`. 
I didn't read carefully the baseline to discover the reason.

**Comment by tinchodias** [comment]
Is it possible that the image where you tried to reproduce this error already had installed the Iterators project (before loading)?

**Comment by juliendelplanque** [comment]
Ah!, I'm finally able to reproduce the problem :-)

**Comment by juliendelplanque** [comment]
Hello, can you try to load [this commit](https://github.com/juliendelplanque/TreeQuery/commit/033e8993da4d44aee9b457579e20b97ae9cd5406) ?

```Smalltalk
Metacello new
    repository: 'github://JulienDelplanque/TreeQuery:033e8993da4d44aee9b457579e20b97ae9cd5406/src';
    baseline: 'TreeQuery';
    load
```

**Comment by tinchodias** [comment]
It loaded and tests passed

**Comment by juliendelplanque** [comment]
Nice, I will create a release.
